version: '3'
services:
    php-solid-server:
        build:
            context: .
        environment:
            # During development it can be useful to set the ENVIRONMENT to "development"
            # in order to see more details about the errors.
            # ENVIRONMENT: development
            USERNAME: alice
            PASSWORD: alice123
            # to run in HTTP mode, set PROXY_MODE
            # PROXY_MODE: true
            PUBSUB_URL: http://pubsub:8080
        ports:
            - 80:80
            - 443:443
        volumes:
          - .:/app/
          # @TODO: The storage directory should be mounted separately
          #        as it really _should_ live outside the code directory
    pubsub:
       build:
           context: https://github.com/pdsinterop/php-solid-pubsub-server.git#main
       ports:
            - 8080:8080
