version: '3'
services:
    php-solid-server:
        build:
            context: .
        environment:
            USERNAME: alice
            PASSWORD: alice123
            PUBSUB_URL: http://pubsub:8080
        ports:
            - 80:80
            - 443:443
    pubsub:
       build:
           context: https://github.com/pdsinterop/php-solid-pubsub-server.git#main
       ports:
            - 8080:8080
