version: '3'
services:
    php-solid-server:
        build:
            context: .
        environment:
            USERNAME: alice
            PASSWORD: alice123
            PUBSUB_URL: http://pubsub:8080
        ports:
            - 80:80
            - 443:443
        volumes:
          - .:/app/
          # @TODO: The storage directory should be mounted separately
          #        as it really _should_ live outside the code directory
    pubsub:
       build:
           context: https://github.com/pdsinterop/php-solid-pubsub-server.git#main
       ports:
            - 8080:8080
